/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new client account */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for an access token */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate a refresh token for a fresh token pair */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a refresh token */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the authenticated user */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users, typically to populate an assignee picker */
        get: operations["UsersController_findMany"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tickets; clients only ever see their own */
        get: operations["TicketsController_findMany"];
        put?: never;
        /** Raise a ticket, stamping its SLA deadlines */
        post: operations["TicketsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregate counts for the agent dashboard */
        get: operations["TicketsController_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a single ticket */
        get: operations["TicketsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a ticket; status and priority changes move the SLA clock */
        patch: operations["TicketsController_update"];
        trace?: never;
    };
    "/api/tickets/{ticketId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List comments; internal notes are hidden from clients */
        get: operations["CommentsController_findMany"];
        put?: never;
        /** Add a comment; an agent reply stops the first-response clock */
        post: operations["CommentsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and dependency check */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example ana@example.com */
            email: string;
            /** @example Ana Anić */
            name: string;
            /** @example super-secret-password */
            password: string;
        };
        AuthUserDto: {
            id: string;
            email: string;
            name: string;
            /** @enum {string} */
            role: "CLIENT" | "AGENT";
        };
        AuthResponseDto: {
            /** @description Short-lived bearer token */
            accessToken: string;
            /** @description Opaque token, rotated on every use */
            refreshToken: string;
            /** Format: date-time */
            refreshTokenExpiresAt: string;
            user: components["schemas"]["AuthUserDto"];
        };
        LoginDto: {
            /** @example agent@example.com */
            email: string;
            /** @example super-secret-password */
            password: string;
        };
        RefreshDto: {
            /** @description The refresh token issued by login, register or a previous refresh */
            refreshToken: string;
        };
        CreateTicketDto: {
            /** @example VPN klijent ne uspostavlja konekciju */
            title: string;
            /** @example Od jutros dobijam error 809 pri konektovanju sa laptopa. */
            description: string;
            /**
             * @default MEDIUM
             * @enum {string}
             */
            priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
        };
        TicketPartyDto: {
            id: string;
            name: string;
            email: string;
            /** @enum {string} */
            role: "CLIENT" | "AGENT";
        };
        SlaClockDto: {
            /** Format: date-time */
            dueAt?: string | null;
            /** Format: date-time */
            metAt?: string | null;
            /** Format: date-time */
            breachedAt?: string | null;
        };
        TicketSlaDto: {
            firstResponse: components["schemas"]["SlaClockDto"];
            resolution: components["schemas"]["SlaClockDto"];
            /** Format: date-time */
            pausedAt?: string | null;
            pausedMinutes: number;
            policyName?: Record<string, never> | null;
        };
        TicketDto: {
            id: string;
            /** @example HD-1042 */
            reference: string;
            title: string;
            description: string;
            /** @enum {string} */
            status: "OPEN" | "IN_PROGRESS" | "WAITING_ON_CUSTOMER" | "RESOLVED" | "CLOSED";
            /** @enum {string} */
            priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
            requester: components["schemas"]["TicketPartyDto"];
            assignee?: components["schemas"]["TicketPartyDto"] | null;
            sla: components["schemas"]["TicketSlaDto"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PaginationMetaDto: {
            page: number;
            pageSize: number;
            total: number;
            totalPages: number;
        };
        PaginatedDto: {
            data: Record<string, never>[];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        TicketStatsDto: {
            total: number;
            /** @description Tickets not yet resolved or closed */
            open: number;
            /** @description Tickets that have breached either SLA clock */
            breached: number;
            /** @description Open tickets with no assignee */
            unassigned: number;
            /**
             * @example {
             *       "OPEN": 4,
             *       "IN_PROGRESS": 2
             *     }
             */
            byStatus: {
                [key: string]: number;
            };
            /**
             * @example {
             *       "LOW": 1,
             *       "URGENT": 3
             *     }
             */
            byPriority: {
                [key: string]: number;
            };
        };
        UpdateTicketDto: {
            title?: string;
            description?: string;
            /** @enum {string} */
            status?: "OPEN" | "IN_PROGRESS" | "WAITING_ON_CUSTOMER" | "RESOLVED" | "CLOSED";
            /** @enum {string} */
            priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
            /** @description Pass null to unassign */
            assigneeId?: Record<string, never> | null;
        };
        CreateCommentDto: {
            /** @example Proverili smo logove, problem je u sertifikatu. */
            body: string;
            /**
             * @description Agents only; hidden from the requester
             * @default false
             */
            isInternal: boolean;
        };
        CommentDto: {
            id: string;
            ticketId: string;
            body: string;
            isInternal: boolean;
            author: components["schemas"]["TicketPartyDto"];
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserDto"];
                };
            };
        };
    };
    UsersController_findMany: {
        parameters: {
            query?: {
                role?: "CLIENT" | "AGENT";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserDto"][];
                };
            };
        };
    };
    TicketsController_findMany: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                status?: ("OPEN" | "IN_PROGRESS" | "WAITING_ON_CUSTOMER" | "RESOLVED" | "CLOSED")[];
                priority?: ("LOW" | "MEDIUM" | "HIGH" | "URGENT")[];
                assigneeId?: string;
                requesterId?: string;
                /** @description Only tickets that have breached any SLA clock */
                breached?: boolean;
                /** @description Only tickets with no assignee */
                unassigned?: boolean;
                /** @description Case-insensitive match on title and description */
                search?: string;
                sortBy?: "createdAt" | "updatedAt" | "priority" | "resolutionDueAt";
                sortOrder?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDto"] & {
                        data?: components["schemas"]["TicketDto"][];
                    };
                };
            };
        };
    };
    TicketsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTicketDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDto"];
                };
            };
        };
    };
    TicketsController_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketStatsDto"];
                };
            };
        };
    };
    TicketsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDto"];
                };
            };
        };
    };
    TicketsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTicketDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDto"];
                };
            };
        };
    };
    CommentsController_findMany: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                ticketId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDto"] & {
                        data?: components["schemas"]["CommentDto"][];
                    };
                };
            };
        };
    };
    CommentsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentDto"];
                };
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
